### ISSUE TITLE
[BUG]:

### ISSUE THREAD

**Issue by mhayta** [KernelWanderers/OCSysInfo#30]
**Describe the bug**
Linux version not work on my asus x555l machine and throw an error:
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 352, in exec_module
  File "info.py", line 24, in <module>
  File "info.py", line 26, in AppInfo
  File "info.py", line 15, in get_latest_version
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIZUp7tu/src/util/version.json'
[230178] Failed to execute script 'main' due to unhandled exception!

**Platform (please complete the following information):**
 - OS: [LinuxMint 21.1]
 - Version []

**Comment by kernel-dev** [comment]
Which release version are you using?

**Comment by mhayta** [comment]
Error in version [v1.0.9-beta], 1.08 working as expected.

**Comment by kernel-dev** [comment]
I don't currently have Linux installed on my machine, so I don't know when I'll be able to get around to this issue. I'll pin this issue. Thank you for bringing it to attention.

**Comment by kernel-dev** [comment]
Hi, @mhayta. I believe the Linux binaries should now be up to date with the latest commit from `releases-source`. Please do let me know if everything's working.

**Comment by mhayta** [comment]
Download this https://github.com/KernelWanderers/OCSysInfo/releases/download/v1.0.9-beta/ocsysinfo_linux_x86_64 .
Working properly. But version info still 1.0.8?
![image](https://github.com/KernelWanderers/OCSysInfo/assets/13572595/7b066c70-8773-4379-ab80-720e057a884c)
